version: 0.2

# Required environment variables:
# - NPM_LOGIN_COMMAND - command to login to CodeArtifact repository
phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.9
    commands:
      - pip3 install cfn-lint --upgrade
      - ${NPM_LOGIN_COMMAND}
  pre_build:
    commands:
      # Inception stage
      - aws --version
      - cfn-lint --version
      - ./deploy.sh
  build:
    commands:
      - cd project
      - npm ci
      - npm test
  post_build:
    commands:
      - npm publish